[package]
name = "Flip_Columns_For_Maximum_Number_of_Equal_Rows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
