[package]
name = "Change_Minimum_Characters_to_Satisfy_One_of_Three_Conditions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
