[package]
name = "Minimum_Number_of_Flips_to_Make_the_Binary_String_Alternating"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
