[package]
name = "Minimum_Insertions_to_Balance_a_Parentheses_String"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
