[package]
name = "Split_a_String_Into_the_Max_Number_of_Unique_Substrings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
