[package]
name = "Minimum_Number_of_Vertices_to_Reach_All_Nodes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
